image:
  file: .gitpod.Dockerfile

tasks:
  - before: >
      sudo apt update ;
      sudo apt install iverilog ;
      pip3 install cocotb ;
      export COCOTB_REDUCED_LOG_FMT=1 ;
      git submodule update --init ;
      cargo install rstbrun
    init: >
      cd /workspace/rstb_examples/test_axis_fifo &&
      cargo build --release
    command: >
      cd /workspace/rstb_examples/test_axis_fifo &&
      gp open hdl/axis_fifo.v &&
      gp open src/tb.rs &&
      gp open src/lib.rs ;
      echo "build & run Rstb test 'rstbrun .'" ;
      echo "run identical Cocotb test with 'make'"

# https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080  # VNC for e.g. gtkwave
    onOpen: notify
  - port: 5900
    onOpen: ignore

vscode:
  extensions:
    - mshr-h.veriloghdl@1.0.6:RPslnvyzniF7C66mxHT+Hg==
    - vhdlwhiz.vhdl-by-vhdlwhiz@1.2.10:fJXQenGkzoZwUN/RddpuSw==
    - matklad.rust-analyzer
    - mhutchie.git-graph
