/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn vl_get_root_handle() -> usize;
}
extern "C" {
    pub fn get_signal_by_name();
}
extern "C" {
    pub fn vl_init();
}
extern "C" {
    pub fn vl_finalize();
}
extern "C" {
    pub fn vl_got_finish() -> bool;
}
extern "C" {
    pub fn vl_get_time() -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn vl_set_time(t: ::std::os::raw::c_ulong);
}
