/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn vl_print_scope(name: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn vl_init();
}
extern "C" {
    pub fn vl_finalize();
}
extern "C" {
    pub fn vl_got_finish() -> bool;
}
extern "C" {
    pub fn vl_get_time() -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn vl_set_time(t: ::std::os::raw::c_ulong);
}
