[package]
name = "test_verilog_types"
version = "0.1.0"
authors = ["benbr8"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
librstb = "*"

[profile.release]
opt-level = 3